package dao.model.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TokenCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table token
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table token
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table token
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table token
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table token
     *
     * @mbg.generated
     */
    protected int pageSize = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    public TokenCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table token
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTokenIdIsNull() {
            addCriterion("token_id is null");
            return (Criteria) this;
        }

        public Criteria andTokenIdIsNotNull() {
            addCriterion("token_id is not null");
            return (Criteria) this;
        }

        public Criteria andTokenIdEqualTo(String value) {
            addCriterion("token_id =", value, "tokenId");
            return (Criteria) this;
        }

        public Criteria andTokenIdNotEqualTo(String value) {
            addCriterion("token_id <>", value, "tokenId");
            return (Criteria) this;
        }

        public Criteria andTokenIdGreaterThan(String value) {
            addCriterion("token_id >", value, "tokenId");
            return (Criteria) this;
        }

        public Criteria andTokenIdGreaterThanOrEqualTo(String value) {
            addCriterion("token_id >=", value, "tokenId");
            return (Criteria) this;
        }

        public Criteria andTokenIdLessThan(String value) {
            addCriterion("token_id <", value, "tokenId");
            return (Criteria) this;
        }

        public Criteria andTokenIdLessThanOrEqualTo(String value) {
            addCriterion("token_id <=", value, "tokenId");
            return (Criteria) this;
        }

        public Criteria andTokenIdLike(String value) {
            addCriterion("token_id like", value, "tokenId");
            return (Criteria) this;
        }

        public Criteria andTokenIdNotLike(String value) {
            addCriterion("token_id not like", value, "tokenId");
            return (Criteria) this;
        }

        public Criteria andTokenIdIn(List<String> values) {
            addCriterion("token_id in", values, "tokenId");
            return (Criteria) this;
        }

        public Criteria andTokenIdNotIn(List<String> values) {
            addCriterion("token_id not in", values, "tokenId");
            return (Criteria) this;
        }

        public Criteria andTokenIdBetween(String value1, String value2) {
            addCriterion("token_id between", value1, value2, "tokenId");
            return (Criteria) this;
        }

        public Criteria andTokenIdNotBetween(String value1, String value2) {
            addCriterion("token_id not between", value1, value2, "tokenId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andTokenCreateTimeIsNull() {
            addCriterion("token_create_time is null");
            return (Criteria) this;
        }

        public Criteria andTokenCreateTimeIsNotNull() {
            addCriterion("token_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andTokenCreateTimeEqualTo(Date value) {
            addCriterion("token_create_time =", value, "tokenCreateTime");
            return (Criteria) this;
        }

        public Criteria andTokenCreateTimeNotEqualTo(Date value) {
            addCriterion("token_create_time <>", value, "tokenCreateTime");
            return (Criteria) this;
        }

        public Criteria andTokenCreateTimeGreaterThan(Date value) {
            addCriterion("token_create_time >", value, "tokenCreateTime");
            return (Criteria) this;
        }

        public Criteria andTokenCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("token_create_time >=", value, "tokenCreateTime");
            return (Criteria) this;
        }

        public Criteria andTokenCreateTimeLessThan(Date value) {
            addCriterion("token_create_time <", value, "tokenCreateTime");
            return (Criteria) this;
        }

        public Criteria andTokenCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("token_create_time <=", value, "tokenCreateTime");
            return (Criteria) this;
        }

        public Criteria andTokenCreateTimeIn(List<Date> values) {
            addCriterion("token_create_time in", values, "tokenCreateTime");
            return (Criteria) this;
        }

        public Criteria andTokenCreateTimeNotIn(List<Date> values) {
            addCriterion("token_create_time not in", values, "tokenCreateTime");
            return (Criteria) this;
        }

        public Criteria andTokenCreateTimeBetween(Date value1, Date value2) {
            addCriterion("token_create_time between", value1, value2, "tokenCreateTime");
            return (Criteria) this;
        }

        public Criteria andTokenCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("token_create_time not between", value1, value2, "tokenCreateTime");
            return (Criteria) this;
        }

        public Criteria andTokenUpdateTimeIsNull() {
            addCriterion("token_update_time is null");
            return (Criteria) this;
        }

        public Criteria andTokenUpdateTimeIsNotNull() {
            addCriterion("token_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andTokenUpdateTimeEqualTo(Date value) {
            addCriterion("token_update_time =", value, "tokenUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTokenUpdateTimeNotEqualTo(Date value) {
            addCriterion("token_update_time <>", value, "tokenUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTokenUpdateTimeGreaterThan(Date value) {
            addCriterion("token_update_time >", value, "tokenUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTokenUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("token_update_time >=", value, "tokenUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTokenUpdateTimeLessThan(Date value) {
            addCriterion("token_update_time <", value, "tokenUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTokenUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("token_update_time <=", value, "tokenUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTokenUpdateTimeIn(List<Date> values) {
            addCriterion("token_update_time in", values, "tokenUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTokenUpdateTimeNotIn(List<Date> values) {
            addCriterion("token_update_time not in", values, "tokenUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTokenUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("token_update_time between", value1, value2, "tokenUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTokenUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("token_update_time not between", value1, value2, "tokenUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeIsNull() {
            addCriterion("token_expire_time is null");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeIsNotNull() {
            addCriterion("token_expire_time is not null");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeEqualTo(Date value) {
            addCriterion("token_expire_time =", value, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeNotEqualTo(Date value) {
            addCriterion("token_expire_time <>", value, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeGreaterThan(Date value) {
            addCriterion("token_expire_time >", value, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("token_expire_time >=", value, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeLessThan(Date value) {
            addCriterion("token_expire_time <", value, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeLessThanOrEqualTo(Date value) {
            addCriterion("token_expire_time <=", value, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeIn(List<Date> values) {
            addCriterion("token_expire_time in", values, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeNotIn(List<Date> values) {
            addCriterion("token_expire_time not in", values, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeBetween(Date value1, Date value2) {
            addCriterion("token_expire_time between", value1, value2, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeNotBetween(Date value1, Date value2) {
            addCriterion("token_expire_time not between", value1, value2, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenIdLikeInsensitive(String value) {
            addCriterion("upper(token_id) like", value.toUpperCase(), "tokenId");
            return (Criteria) this;
        }

        public Criteria andUserIdLikeInsensitive(String value) {
            addCriterion("upper(user_id) like", value.toUpperCase(), "userId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table token
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table token
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}