package org.startpoint.model.base;

import java.io.Serializable;
import java.util.Date;

public class Token implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.token_id
     *
     * @mbg.generated
     */
    private String tokenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.token_create_time
     *
     * @mbg.generated
     */
    private Date tokenCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.token_update_time
     *
     * @mbg.generated
     */
    private Date tokenUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.token_expire_time
     *
     * @mbg.generated
     */
    private Date tokenExpireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table token
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.token_id
     *
     * @return the value of token.token_id
     *
     * @mbg.generated
     */
    public String getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.token_id
     *
     * @param tokenId the value for token.token_id
     *
     * @mbg.generated
     */
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId == null ? null : tokenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.user_id
     *
     * @return the value of token.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.user_id
     *
     * @param userId the value for token.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.token_create_time
     *
     * @return the value of token.token_create_time
     *
     * @mbg.generated
     */
    public Date getTokenCreateTime() {
        return tokenCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.token_create_time
     *
     * @param tokenCreateTime the value for token.token_create_time
     *
     * @mbg.generated
     */
    public void setTokenCreateTime(Date tokenCreateTime) {
        this.tokenCreateTime = tokenCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.token_update_time
     *
     * @return the value of token.token_update_time
     *
     * @mbg.generated
     */
    public Date getTokenUpdateTime() {
        return tokenUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.token_update_time
     *
     * @param tokenUpdateTime the value for token.token_update_time
     *
     * @mbg.generated
     */
    public void setTokenUpdateTime(Date tokenUpdateTime) {
        this.tokenUpdateTime = tokenUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.token_expire_time
     *
     * @return the value of token.token_expire_time
     *
     * @mbg.generated
     */
    public Date getTokenExpireTime() {
        return tokenExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.token_expire_time
     *
     * @param tokenExpireTime the value for token.token_expire_time
     *
     * @mbg.generated
     */
    public void setTokenExpireTime(Date tokenExpireTime) {
        this.tokenExpireTime = tokenExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Token other = (Token) that;
        return (this.getTokenId() == null ? other.getTokenId() == null : this.getTokenId().equals(other.getTokenId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getTokenCreateTime() == null ? other.getTokenCreateTime() == null : this.getTokenCreateTime().equals(other.getTokenCreateTime()))
            && (this.getTokenUpdateTime() == null ? other.getTokenUpdateTime() == null : this.getTokenUpdateTime().equals(other.getTokenUpdateTime()))
            && (this.getTokenExpireTime() == null ? other.getTokenExpireTime() == null : this.getTokenExpireTime().equals(other.getTokenExpireTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTokenId() == null) ? 0 : getTokenId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getTokenCreateTime() == null) ? 0 : getTokenCreateTime().hashCode());
        result = prime * result + ((getTokenUpdateTime() == null) ? 0 : getTokenUpdateTime().hashCode());
        result = prime * result + ((getTokenExpireTime() == null) ? 0 : getTokenExpireTime().hashCode());
        return result;
    }
}