package org.startpoint.model.base;

import java.io.Serializable;
import java.util.Date;

public class UserGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.user_group_id
     *
     * @mbg.generated
     */
    private String userGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.user_group_name
     *
     * @mbg.generated
     */
    private String userGroupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.user_group_parent_id
     *
     * @mbg.generated
     */
    private String userGroupParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.user_group_create_time
     *
     * @mbg.generated
     */
    private Date userGroupCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.user_group_update_time
     *
     * @mbg.generated
     */
    private Date userGroupUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.user_group_state
     *
     * @mbg.generated
     */
    private Byte userGroupState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.user_group_top_id
     *
     * @mbg.generated
     */
    private String userGroupTopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_group
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.user_group_id
     *
     * @return the value of user_group.user_group_id
     *
     * @mbg.generated
     */
    public String getUserGroupId() {
        return userGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.user_group_id
     *
     * @param userGroupId the value for user_group.user_group_id
     *
     * @mbg.generated
     */
    public void setUserGroupId(String userGroupId) {
        this.userGroupId = userGroupId == null ? null : userGroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.user_group_name
     *
     * @return the value of user_group.user_group_name
     *
     * @mbg.generated
     */
    public String getUserGroupName() {
        return userGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.user_group_name
     *
     * @param userGroupName the value for user_group.user_group_name
     *
     * @mbg.generated
     */
    public void setUserGroupName(String userGroupName) {
        this.userGroupName = userGroupName == null ? null : userGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.user_group_parent_id
     *
     * @return the value of user_group.user_group_parent_id
     *
     * @mbg.generated
     */
    public String getUserGroupParentId() {
        return userGroupParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.user_group_parent_id
     *
     * @param userGroupParentId the value for user_group.user_group_parent_id
     *
     * @mbg.generated
     */
    public void setUserGroupParentId(String userGroupParentId) {
        this.userGroupParentId = userGroupParentId == null ? null : userGroupParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.user_group_create_time
     *
     * @return the value of user_group.user_group_create_time
     *
     * @mbg.generated
     */
    public Date getUserGroupCreateTime() {
        return userGroupCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.user_group_create_time
     *
     * @param userGroupCreateTime the value for user_group.user_group_create_time
     *
     * @mbg.generated
     */
    public void setUserGroupCreateTime(Date userGroupCreateTime) {
        this.userGroupCreateTime = userGroupCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.user_group_update_time
     *
     * @return the value of user_group.user_group_update_time
     *
     * @mbg.generated
     */
    public Date getUserGroupUpdateTime() {
        return userGroupUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.user_group_update_time
     *
     * @param userGroupUpdateTime the value for user_group.user_group_update_time
     *
     * @mbg.generated
     */
    public void setUserGroupUpdateTime(Date userGroupUpdateTime) {
        this.userGroupUpdateTime = userGroupUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.user_group_state
     *
     * @return the value of user_group.user_group_state
     *
     * @mbg.generated
     */
    public Byte getUserGroupState() {
        return userGroupState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.user_group_state
     *
     * @param userGroupState the value for user_group.user_group_state
     *
     * @mbg.generated
     */
    public void setUserGroupState(Byte userGroupState) {
        this.userGroupState = userGroupState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.user_group_top_id
     *
     * @return the value of user_group.user_group_top_id
     *
     * @mbg.generated
     */
    public String getUserGroupTopId() {
        return userGroupTopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.user_group_top_id
     *
     * @param userGroupTopId the value for user_group.user_group_top_id
     *
     * @mbg.generated
     */
    public void setUserGroupTopId(String userGroupTopId) {
        this.userGroupTopId = userGroupTopId == null ? null : userGroupTopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserGroup other = (UserGroup) that;
        return (this.getUserGroupId() == null ? other.getUserGroupId() == null : this.getUserGroupId().equals(other.getUserGroupId()))
            && (this.getUserGroupName() == null ? other.getUserGroupName() == null : this.getUserGroupName().equals(other.getUserGroupName()))
            && (this.getUserGroupParentId() == null ? other.getUserGroupParentId() == null : this.getUserGroupParentId().equals(other.getUserGroupParentId()))
            && (this.getUserGroupCreateTime() == null ? other.getUserGroupCreateTime() == null : this.getUserGroupCreateTime().equals(other.getUserGroupCreateTime()))
            && (this.getUserGroupUpdateTime() == null ? other.getUserGroupUpdateTime() == null : this.getUserGroupUpdateTime().equals(other.getUserGroupUpdateTime()))
            && (this.getUserGroupState() == null ? other.getUserGroupState() == null : this.getUserGroupState().equals(other.getUserGroupState()))
            && (this.getUserGroupTopId() == null ? other.getUserGroupTopId() == null : this.getUserGroupTopId().equals(other.getUserGroupTopId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserGroupId() == null) ? 0 : getUserGroupId().hashCode());
        result = prime * result + ((getUserGroupName() == null) ? 0 : getUserGroupName().hashCode());
        result = prime * result + ((getUserGroupParentId() == null) ? 0 : getUserGroupParentId().hashCode());
        result = prime * result + ((getUserGroupCreateTime() == null) ? 0 : getUserGroupCreateTime().hashCode());
        result = prime * result + ((getUserGroupUpdateTime() == null) ? 0 : getUserGroupUpdateTime().hashCode());
        result = prime * result + ((getUserGroupState() == null) ? 0 : getUserGroupState().hashCode());
        result = prime * result + ((getUserGroupTopId() == null) ? 0 : getUserGroupTopId().hashCode());
        return result;
    }
}